blank_issues_enabled: false
contact_links:
  - name: Вопрос по использованию
    url: https://github.com
    about: Для вопросов по эксплуатации создайте Discussion (если включено) или Issue по шаблону feature request.
